name: Lint

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]
  
jobs:
  lint:
    name: Run awesome linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3
      - name: Set up node 🏗
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Lint 🧪
        run: npx awesome-lint
